---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starcafe-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: starcafe
  template:
    metadata:
      labels:
        app: starcafe
    spec:
      containers:
      - name: starcafe
        image: harshvardhan44/starcafe
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: starcafe-service
spec:
  type: LoadBalancer
  selector:
    app: starcafe
  ports:
  - port: 80
    targetPort: 3000
